services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=en,es  # Solo carga inglés y español (reduce RAM)
      - LT_REQUIRE_API_KEY=false  # Opcional: desactiva clave API
      - WAITRESS_THREADS=8  # Hilos paralelos (ajusta según CPUs disponibles)
      - WAITRESS_CHANNEL_TIMEOUT=30  # Tiempo máximo por tarea (segundos)
      - LT_RATE_LIMIT=10  # Límite de peticiones/segundo por IP
      - WAITRESS_THREADS=8
      - LT_WORKERS=2
    restart: unless-stopped